### PR TITLE
validate date iso string

### PR DESCRIPTION
**Pull request by marcosafmartins92**
Creating validation for ISOString date

### CODE REVIEW

**Comment by pleerock** [comment]
please update docs about new decorator

**Comment by marcosafmartins92** [comment]
ok, I will update docs soon.

**Comment by marcosafmartins92** [comment]
done

**Comment by marcosafmartins92** [comment]
Hi! I did what you ask for, please review my pr :smile: 
thanks

**Comment by pleerock** [comment]
thanks for the pr!

**Comment by pleerock** [comment]
released in `0.7.1`

**Pull request merged**
